<?php

/**
 * @file
 * Provide the functions for the Catalog Pointer module
 */

// pulls var from admin form
function catalog_pointer_url(){
  global $catalogTarget;
  $catalogTarget = variable_get('catalog_pointer_target', 'http://findit.library.gwu.edu/search');
  return $catalogTarget;
}

// checks to see if the Default target is selected
function catalog_pointer_check(){
  $catalogCheckbox = variable_get('catalog_pointer_default', '1');
  if ($catalogCheckbox == 1) {
    $catalogTarget = 'http://findit.library.gwu.edu/search';
  }
  else {
    $catalogTarget = catalog_pointer_url();
  }
  return $catalogTarget;
}

 /**
 * Defines the Catalog Pointer admin settings form 
 */
//function catalog_pointer_admin_settings_form() {
//  $form['catalog_target'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Target URL for the Catalog Search'),
//    '#default_value' => variable_get('catalog_target', t('http://findit.library.gwu.edu/search')),
//  );
//  return system_settings_form($form);
//}

/* more... */

function catalog_pointer_menu() {
  $items = array();

  $items['admin/config/content/catalog_pointer'] = array(
    'title' => 'Catalog Search Configuration',
    'description' => t('Configuration for the Catalog Search. Use this the change the target URL for the Catalog Search.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('catalog_pointer_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function catalog_pointer_form($form, &$form_state) {
    $form['catalog_pointer_default'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use the Default Catalog Target'),
    '#default_value' => variable_get('catalog_pointer_default', 1),
    '#description' => t('Use the default catalog target (Summon) http://findit.library.gwu.edu/search. IMPORTANT: if this is unchecked, the catalog will use the url supplied in the textfield below'),
    '#required' => FALSE,
  );

  $form['catalog_pointer_target'] = array(
    '#type' => 'textfield',
    '#title' => t('Alternate Catalog URL'),
    '#default_value' => variable_get('catalog_pointer_target', 'http://findit.library.gwu.edu/search'),
    '#size' => 40,
    '#maxlength' => 80,
    '#description' => t('<p>(uncheck the Default Catalog Target box to use this) Target URL for the Libraries catalog search.</p> <ul><li>Default catalog URL (Summon is up) http://findit.library.gwu.edu/search</li><li>Test/beta catalog URL: http://gwfindit-beta.wrlc.org/search</li><li>Fallback catalog URL (Summon is down): http://discovery.wrlc.org</li></ul><p>Currently the search string sent to the WRLC Catalog doesn"t return any results. I may change this to a select menu that will also update the appended vars sent from the form.</p><p>On the production site you will need to clear the site cache at <a href="/admin/config/development/performance">/admin/config/development/performance</a></p>'),
    '#required' => TRUE,
  );



  return system_settings_form($form);
 
}
