<?php

/**
 * @file
 * Provide the functions for the Catalog Pointer module
 */

// pulling var from new admin form (test)
global $catalogTarget;
$catalogTarget = variable_get('catalog_pointer_target', 'http://findit.library.gwu.edu/search');


 /**
 * Defines the Catalog Pointer admin settings form 
 */
//function catalog_pointer_admin_settings_form() {
//  $form['catalog_target'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Target URL for the Catalog Search'),
//    '#default_value' => variable_get('catalog_target', t('http://findit.library.gwu.edu/search')),
//  );
//  return system_settings_form($form);
//}

/* more... */

function catalog_pointer_menu() {
  $items = array();

  $items['admin/config/content/catalog_pointer'] = array(
    'title' => 'Catalog Search Configuration',
    'description' => t('Configuration for the Catalog Search. Use this the change the target URL for the Catalog Search. <ul><li>Default target (Summon is up) http://findit.library.gwu.edu</li><li>Test/beta: http://gwfindit-beta.wrlc.org)</li><li>The fallback if Summon is down: http://discovery.wrlc.org</li></ul>'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('catalog_pointer_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function catalog_pointer_form($form, &$form_state) {
  $form['catalog_pointer_target'] = array(
    '#type' => 'textfield',
    '#title' => t('Catalog Pointer'),
    '#default_value' => variable_get('catalog_pointer_target', 'http://findit.library.gwu.edu/search'),
    '#size' => 40,
    '#maxlength' => 80,
    '#description' => t('Target URL for the Libraries catalog search (testing).'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
